version: "3.8"

services:
  api:
    image: fastapi_sqlmodel_security
    container_name: fastapi_sqlmodel_security_dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FASTAPI_SQLMODEL_SECURITY_SECRET=TEST_SECRET
    ports:
      - target: 80
        published: 8080
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: bind
        source: ./fastapi_sqlmodel_security
        target: /app/fastapi_sqlmodel_security
    command: /start-reload.sh
