[tool.poetry]
name = "fastapi_simple_security"
version = "1.1"
description = "API key-based security for FastAPI"
authors = ["mrtolkien <gary.mialaret@gmail.com>"]
license = "MIT"
repository = "https://github.com/mrtolkien/fastapi_simple_security"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7,<4"
# 0.70 is needed to have the TestClient object
fastapi = ">=0.70"
# Necessary as older versions don't work on python 3.10
urllib3 = ">=1.26.12"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
black = {version = "^21.12b0", allow-prereleases = true}
requests = "^2.26.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
