on:
  workflow_dispatch:

name: PyPI Package Release

jobs:
  release-please:
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Get the files
      - uses: actions/checkout@v3

      # Python setup
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.2.0
        with:
          poetry-version: 1.4.2

      - name: Install python dependencies
        run: |
          poetry install

      - name: Run Python tests
        run: |
          poetry run coverage run -m pytest -s tests

      - name: Build and publish
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build
